name: Create Release Draft

on:
  push:
    branches:
      - main
    paths:
      - '.github/release/release_details.json'
  workflow_dispatch:

jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          JSON_FILE=".github/release/release_details.json"
          
          # Parse JSON
          RELEASE_NAME=$(jq -r '.release_name' $JSON_FILE)
          START_DATE=$(jq -r '.start_date' $JSON_FILE)
          CHANGE_SUMMARY=$(jq -r '.change_summary' $JSON_FILE)
          RELEASE_DATE=$(echo "$START_DATE" | cut -d' ' -f1)
          TAG_NAME="release-${RELEASE_DATE}"
          
          # Build artefacts table
          ARTEFACTS_TABLE="| Image | Tag |\n|-------|-----|\n"
          while read -r artifact_url; do
            IMAGE_NAME=$(echo "$artifact_url" | sed 's|.*/||' | cut -d: -f1)
            IMAGE_TAG=$(echo "$artifact_url" | sed 's|.*:||')
            ARTEFACTS_TABLE="${ARTEFACTS_TABLE}| ${IMAGE_NAME} | \`${IMAGE_TAG}\` |\n"
          done < <(jq -r '.artefact[]' $JSON_FILE)
          
          # Build release body
          BODY="## ${RELEASE_NAME}

          **Released:** ${START_DATE}

          ---

          ## Summary

          ${CHANGE_SUMMARY}

          ---

          ## Artefacts

          $(echo -e "$ARTEFACTS_TABLE")"
          
          # Escape for JSON
          BODY_ESCAPED=$(echo "$BODY" | jq -Rs .)
          
          # Create release via GitHub API
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{
              \"tag_name\": \"${TAG_NAME}\",
              \"target_commitish\": \"${{ github.sha }}\",
              \"name\": \"${RELEASE_NAME}\",
              \"body\": ${BODY_ESCAPED},
              \"draft\": true,
              \"prerelease\": false
            }"
          
          # Output summary
          echo "## ✅ Release Draft Created" >> $GITHUB_STEP_SUMMARY
          echo "**Release:** $RELEASE_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** $TAG_NAME" >> $GITHUB_STEP_SUMMARY
